### ISSUE TITLE
Actor Names Not reflected in Token Names

### ISSUE THREAD

**Issue by discuit** [yochaigal/Cairn-FoundryVTT#21] opened 2021-05-04 22:57 UTC
Just FYI, we had our first game tonight, and we noticed that when you change an actors name it somehow keeps the old name on the tokens. Thanks!

**Comment by danielbackus** [comment] 2021-08-24 13:51
I think this is not a bug, but default Foundry behavior?

A fix might be outside the scope of this system, but looks like there are some module options like https://foundryvtt.com/packages/sync-token-names

**Comment by oswida** [comment] 2024-10-03 21:03
Closing as it looks like Foundry feature. It seems that tokens put on the scene are not synchronized with actor entry in actor list. It can be caused by the fact, that you can have multiple tokens (even on different scenes) for the same actor entity, so it is possible that for each token there is a copy of actor created.

**Closed by oswida** 2024-10-03 21:03 UTC
